ServerEvents.recipes(e => {
	e.remove({ mod: 'ultimine_addition' })

	e.remove({ id: 'casting:melting/iron/from_dust' })
	e.remove({ id: 'casting:melting/black_brick/from_clay_block' })

	e.remove({ id: 'casting:solidifier/iron/dust' })
	e.remove({ id: 'casting:solidifier/stone/block' })
	e.remove({ id: 'casting:solidifier/silicon/block' })
	e.remove({ id: 'casting:solidifier/fluix/block' })
	e.remove({ id: 'casting:solidifier/fluix/crystal' })
	e.remove({ id: 'casting:solidifier/glass/block' })
	e.remove({ id: 'casting:solidifier/charged_certus_quartz/crystal' })
	e.remove({ id: 'casting:solidifier/certus_quartz/crystal' })
	e.remove({ id: 'casting:solidifier/certus_quartz/block' })
	e.remove({ id: 'casting:solidifier/diamond/storage_block' })
	e.remove({ id: 'casting:solidifier/diamond/gem' })
	e.remove({ id: 'casting:solidifier/diamond/dust' })
	e.remove({ id: 'casting:solidifier/emerald/storage_block' })
	e.remove({ id: 'casting:solidifier/emerald/gem' })
	e.remove({ id: 'casting:solidifier/emerald/dust' })
	e.remove({ id: 'casting:solidifier/debris/netherite_scrap' })
	e.remove({ id: 'casting:solidifier/netherite/storage_block' })
	e.remove({ id: 'casting:solidifier/netherite/ingot' })
	e.remove({ id: 'casting:solidifier/end_stone/block' })
	e.remove({ id: 'casting:solidifier/ender/ender_pearl' })
	e.remove({ id: 'casting:solidifier/steel/ingot' })
	e.remove({ id: 'casting:solidifier/steel/plate' })
	e.remove({ id: 'casting:solidifier/steel/storage_block' })
	e.remove({ id: 'casting:solidifier/invar/ingot' })
	e.remove({ id: 'casting:solidifier/invar/storage_block' })
	e.remove({ id: 'casting:solidifier/invar/nugget' })
	e.remove({ id: 'casting:solidifier/invar/dust' })
	e.remove({ id: 'casting:solidifier/invar/plate' })
	e.remove({ id: 'casting:solidifier/invar/rod' })
	e.remove({ id: 'casting:solidifier/invar/gear' })
	e.remove({ id: 'casting:solidifier/electrum/ingot' })
	e.remove({ id: 'casting:solidifier/electrum/storage_block' })
	e.remove({ id: 'casting:solidifier/electrum/nugget' })
	e.remove({ id: 'casting:solidifier/electrum/dust' })
	e.remove({ id: 'casting:solidifier/electrum/plate' })
	e.remove({ id: 'casting:solidifier/electrum/rod' })
	e.remove({ id: 'casting:solidifier/electrum/gear' })
	e.remove({ id: 'casting:solidifier/bronze/ingot' })
	e.remove({ id: 'casting:solidifier/bronze/dust' })
	e.remove({ id: 'casting:solidifier/bronze/storage_block' })
	e.remove({ id: 'casting:solidifier/bronze/plate' })
	e.remove({ id: 'casting:solidifier/uranium/ingot' })
	e.remove({ id: 'casting:solidifier/uranium/storage_block' })
	e.remove({ id: 'casting:solidifier/lapis/plate' })
	e.remove({ id: 'casting:solidifier/lapis/dust' })
	e.remove({ id: 'casting:solidifier/lapis/storage_block' })
	e.remove({ id: 'casting:solidifier/lapis/gem' })
	e.remove({ id: 'casting:solidifier/redstone/dust' })
	e.remove({ id: 'casting:solidifier/redstone/storage_block' })
	e.remove({ id: 'casting:solidifier/coal/coal' })
	e.remove({ id: 'casting:solidifier/coal/coal_block' })
	e.remove({ id: 'casting:solidifier/glowstone/block' })
	e.remove({ id: 'casting:solidifier/glowstone/dust' })
	e.remove({ id: 'casting:solidifier/quartz/dust' })
	e.remove({ id: 'casting:solidifier/quartz/block' })
	e.remove({ id: 'casting:solidifier/quartz/gem' })
	e.remove({ id: 'casting:solidifier/blaze/rod' })
	e.remove({ id: 'casting:solidifier/blaze/dust' })
	e.remove({ id: 'casting:solidifier/sapphire/gem' })
	e.remove({ id: 'casting:solidifier/sapphire/storage_block' })
	e.remove({ id: 'casting:solidifier/ruby/gem' })
	e.remove({ id: 'casting:solidifier/ruby/storage_block' })
	e.remove({ id: 'casting:solidifier/soul/block' })
	e.remove({ id: 'casting:solidifier/obsidian/block' })
	e.remove({ id: 'casting:solidifier/nickel/dust' })
	e.remove({ id: 'casting:solidifier/platinum/dust' })
	e.remove({ id: 'casting:solidifier/gold/dust' })
	e.remove({ id: 'casting:solidifier/silver/dust' })
	e.remove({ id: 'casting:solidifier/zinc/dust' })
	e.remove({ id: 'casting:solidifier/iridium/dust' })
	e.remove({ id: 'casting:solidifier/copper/dust' })
	e.remove({ id: 'casting:solidifier/tin/dust' })
	e.remove({ id: 'casting:solidifier/lead/dust' })
	e.remove({ id: 'casting:solidifier/osmium/dust' })
	
	e.remove({ output: 'casting:multiblock_controller' })
	e.remove({ output: 'casting:multiblock_coolant_tank' })
	e.remove({ output: 'casting:multiblock_solidifier' })
	e.remove({ output: 'casting:multiblock_valve' })
	e.remove({ output: 'casting:multiblock_mixer' })
	e.remove({ output: 'casting:mixer' })
	e.remove({ output: 'casting:multiblock_fuel_tank' })
	e.remove({ output: 'casting:equipment_modifier' })
})

RecipeViewerEvents.removeEntries('item', e => {
	e.remove('@ultimine_addition')
	e.remove('casting:molten_diamond_bucket')
})

RecipeViewerEvents.removeEntries('fluid', e => {
	e.remove('casting:molten_diamond')
})

RecipeViewerEvents.removeCategories(event => {
	event.remove('jei:information')
	event.remove('casting:mixing')
	event.remove('casting:equipment_modifier')
})